CREATE TABLE "fact_youtube_performance" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "video_id" varchar NOT NULL,
  "date" date NOT NULL,
  "views" bigint,
  "unique_views" int,
  "watch_time_hours" decimal(12,2),
  "avg_view_duration" decimal(8,2),
  "impression_ctr" decimal(5,4),
  "likes" int,
  "comments" int,
  "shares" int,
  "retention_rate" decimal(5,4),
  "subscribers_gained" int,
  "channel_id" varchar,
  "content_length_category" varchar,
  "traffic_source" varchar,
  "device_type" varchar,
  "is_live" boolean
);

CREATE TABLE "dim_video" (
  "video_id" varchar PRIMARY KEY,
  "title" varchar(200),
  "description" text,
  "publish_date" date,
  "duration_seconds" int,
  "channel_id" varchar,
  "tags" text,
  "thumbnail_url" varchar(500),
  "language" varchar(10),
  "is_monetized" boolean,
  "category_id" varchar,
  "privacy_status" varchar(20)
);

CREATE TABLE "dim_channel" (
  "channel_id" varchar PRIMARY KEY,
  "channel_name" varchar,
  "category" varchar,
  "created_at" date,
  "country" varchar(2),
  "subscriber_count" bigint,
  "total_videos" int,
  "is_verified" boolean,
  "custom_url" varchar(100),
  "description" text,
  "banner_url" varchar(500)
);

CREATE TABLE "dim_content_length" (
  "content_length_category" varchar PRIMARY KEY,
  "definition" varchar
);

CREATE TABLE "dim_date" (
  "date_id" int PRIMARY KEY,
  "date" date UNIQUE,
  "year" int,
  "quarter" int,
  "month" int,
  "month_name" varchar(20),
  "week_of_year" int,
  "day_of_month" int,
  "day_of_week" int,
  "day_name" varchar(20),
  "is_weekend" boolean,
  "is_holiday" boolean
);

ALTER TABLE "fact_youtube_performance" ADD FOREIGN KEY ("video_id") REFERENCES "dim_video" ("video_id");

ALTER TABLE "fact_youtube_performance" ADD FOREIGN KEY ("date") REFERENCES "dim_date" ("date");

ALTER TABLE "fact_youtube_performance" ADD FOREIGN KEY ("channel_id") REFERENCES "dim_channel" ("channel_id");

ALTER TABLE "fact_youtube_performance" ADD FOREIGN KEY ("content_length_category") REFERENCES "dim_content_length" ("content_length_category");

ALTER TABLE "dim_video" ADD FOREIGN KEY ("channel_id") REFERENCES "dim_channel" ("channel_id");
